-- noinspection SqlNoDataSourceInspectionForFile

CREATE SCHEMA DEMO_SCHEMA;

CREATE SEQUENCE DEMO_SCHEMA.ACCOUNT_SEQ
    START WITH50002
    INCREMENT BY 1;

CREATE TABLE DEMO_SCHEMA.ACCOUNT_TYPE
(
    ACCOUNT_TYPE BIGINT     NOT NULL;
    MNEMONIC    VARCHAR(100) NOT NULL UNIQUE;
    ACCOUNT_TYPE_NAME   VARCHAR(255) NOT NULL,
    CREATION_DATE   DATE NOT NULL,
    PRIMARY KEY (ACCOUNT_TYPE_ID)
);

CREATE TABLE DEMO_SCHEMA.ACCOUNT_TX
(
    TX_ID BIGINT    NOT NULL,
    ACCOUNT_TYPE_ID BIGINT  NOT NULL,
    MEMBER_ID BIGINT    NOT NULL,
    AMOUNT BIGINT NOT NULL,
    TX_DATE     DATE    NOT NULL,
    PRIMARY KEY (TX_ID),
    CONSTRAINT FK_ACCOUNT_TYPE_ID FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES DEMO_SCHEMA.ACCOUNT_TYPE (ACCOUNT_TYPE_ID)
);